# Generated by Django 3.1 on 2020-08-31 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('New', 'New'), ('Done', 'Done'), ('In Progress', 'In Progress'), ('Invalid', 'Invalid')], max_length=15)),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketAssigned', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketAuthor', to=settings.AUTH_USER_MODEL)),
                ('completer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketCompleter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
